export const actionTypes = Object.freeze({
  //Auth
  LOGIN: "AUTH/LOGIN",
  LOGOUT: "AUTH/LOGOUT",
  REGISTRATION: "AUTH/REGISTRATION",
  CHECK_AUTH_STATUS: "AUTH/CHECK_AUTH_STATUS",
  //Profile
  SET_USER: "USER/SET_USER",
  SET_USER_LOADING: "USER/SET_USER_LOADING",
  SET_USER_AUTH_STATUS: "USER/SET_USER_AUTH_STATUS",
  CLEAR_USER_DATA: "USER/CLEAR",
  //Users
  GET_ALL_USERS: "USER/GET_ALL_USERS",
});
